### Production environment settings

# STS role and target account
sts_role_arn: arn:aws:iam::543279062384:role/admin

# ECR Repositories
config_ecr_repos:
  dockerproductionaws/microtrader-base: {}
  dockerproductionaws/microtrader-audit: {}
  dockerproductionaws/microtrader-dashboard: {}
  dockerproductionaws/microtrader-portfolio: {}
  dockerproductionaws/microtrader-quote: {}
  dockerproductionaws/squid: {}
  dockerproductionaws/ntp: {}
  dockerproductionaws/codebuild:
    ro_services:
      - codebuild.amazonaws.com